routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('prod/add', 'ProdController@create');
Route::get('prod/{prod}/delete', [
    'as'   => 'prod.delete',
    'uses' => 'ProdController@destroy',
]);
Route::resource('/prod', 'ProdController');

Route::get('recipes/add', 'RecipesController@create');
Route::get('recipes/{recipes}/delete', [
    'as'   => 'recipes.delete',
    'uses' => 'RecipesController@destroy',
]);
Route::resource('/recipes', 'RecipesController');


function is_active_sorter($key, $direction = 'ASC')
{
    if (request('sortby') == $key && request('sortdir') == $direction) {
        return true;
    }

    return false;
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="panel panel-default">
          <div class="panel-heading">
            @if (auth()->check())
              <strong>
                {{ auth()->user()->name }}
              </strong>
            @endif
          </div>

          <div class="panel-body">
            @if (auth()->guest())
              Для доступу до <a href="{{ route('prod.index') }}">сторінки продуктів</a>,
              вам потрібно
              <a href="/register">зареєструвати</a> аккаунт.
              You will automatically logged in after registered.
            @else
              <a href="{{ route('prod.index') }}">Сторінка продуктів</a>
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection