routes/web.php
<?php

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('prod/add', 'ProdController@create');
Route::get('prod/{prod}/delete', [
    'as'   => 'prod.delete',
    'uses' => 'ProdController@destroy',
]);
Route::resource('/prod', 'ProdController');

Route::get('recipes/add', 'RecipesController@create');
Route::get('recipes/{recipes}/delete', [
    'as'   => 'recipes.delete',
    'uses' => 'RecipesController@destroy',
]);
Route::resource('/recipes', 'RecipesController');


function is_active_sorter($key, $direction = 'ASC')
{
    if (request('sortby') == $key && request('sortdir') == $direction) {
        return true;
    }

    return false;
}

resources/views/resipes/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">

    <form method="POST" action="/recipes">

      <div class="clearfix">
        <div class="pull-left">
          <div class="lead">
            <strong>Додати новий рецепт</strong>
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-success">Зберегти</button>
          <a href="/recipes" class="btn btn-default">До списку</a>
        </div>
      </div>
      <hr>

      @include('resipes.form')
    </form>

  </div>
@endsection

resources/views/resipes/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">

    <form method="POST" action="/recipes/{{ $resipes->id }}">

      <div class="clearfix">
        <div class="pull-left">
          <div class="lead">
            <strong>Редагування рецепту</strong>
            <small>"{{ $resipes->title }}"</small>
          </div>
        </div>
        <div class="pull-right">
          <button type="submit" class="btn btn-success">Зберегти</button>
          <a href="/recipes" class="btn btn-default">До списку</a>
        </div>
      </div>
      <hr>

      {!! method_field('PUT') !!}
      @include('resipes.form')
    </form>

  </div>
@endsection

resources/views/resipes/form.blade.php
{!! csrf_field() !!}

<input type="hidden" name="id" id="id" value="{{ old('id', @$resipes->id) }}">

<select style="display: none;" id="count_type">
  @foreach($prod->typeCount as $type)
    <option value="{{$type}}">{{$type}}</option>
  @endforeach
</select>

<div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">

  <label for="title" class="control-label">
    Назва рецепту
  </label>

  <input type="text"
         name="title"
         id="title"
         value="{{ old('title', @$resipes->title) }}"
         placeholder="Назва рецепту"
         required
         class="form-control">

  @if ($errors->has('title'))
    <div class="help-block">
      {{ $errors->first('title') }}
    </div>
  @endif
</div>

<div id="components">
  @php
    $i = 1;
  @endphp
  @if($components = $resipes->components)
    @foreach($components as $component)
      <div class="form-group" id="mainBlock{{$i}}">
        <label class="control-label">Інгредієнт {{$i}}</label>
        <input class="form-control" name="components_name[{{$i}}]" placeholder="Назва інгредієнта" style="margin-bottom: 10px;" value="{{$component->name}}">
        <div class="row">
          <div class="col-xs-7">
            <input class="form-control" name="components[{{$i}}]" type="number" placeholder="Кількість інгредієнту" value="{{$component->count}}">
          </div>
          <div class="col-xs-2">
            <select style="display: block;" id="components_type{{$i}}" class="form-control" name="components_type[{{$i}}]">
              @foreach($prod->typeCount as $type)
                <option value="{{$type}}" {{($type == $component->count_type) ? 'selected' : ''}}>{{$type}}</option>
              @endforeach
            </select>
          </div>
          <div class="col-xs-1">
            <input class="form-control" name="components_change[{{$i}}]" type="checkbox" title="Можливість заміни компоненту" id="components_change{{$i}}" {{($component->possibility_of_replacement == 'on') ? 'checked' : ''}}>
          </div>
          <div class="col-xs-2">
              <input style="margin-bottom: 15px" type="button" class="btn btn-danger" value="Видалити" onclick="deleteBlock({{$i}})">
          </div>
        </div>
      </div>
      @php
        $i++;
      @endphp
    @endforeach
  @endif
  <input type="hidden" value="{{$i}}" id="countComponents">
</div>

<input class="btn btn-info" type="button" onclick="add_component();" value="Додати інгредієнт" style="margin-bottom: 20px">
<script>
    var components = document.getElementById("components");
    var length = document.getElementById("countComponents").value;

    function deleteBlock(i) {
        var elem = document.getElementById("mainBlock" + i);
        return elem.parentNode.removeChild(elem);
    }

    function add_component() {
        var new_input = document.createElement("input");
        new_input.classList.add("form-control");
        new_input.name = "components["+length+"]";
        new_input.type = "number";
        new_input.placeholder = "Кількість інгредієнту";

        var new_select = document.getElementById("count_type");
        var new_select_type = new_select.cloneNode(true);
        new_select_type.classList.add("form-control");
        new_select_type.style.display = "block";
        new_select_type.name = "components_type["+length+"]";
        new_select_type.id = "components_type" + length;

        var new_input1 = document.createElement("input");
        new_input1.classList.add("form-control");
        new_input1.name = "components_change["+length+"]";
        new_input1.type = "checkbox";
        new_input1.title = "Можливість заміни компоненту";
        new_input1.id = "components_change" + length;

        var div = document.createElement('div');
        div.classList.add("form-group");
        div.id = "mainBlock" + length;
        div.innerHTML = "<label for='" + new_input.name + "' class='control-label'>Інгредієнт " + length + "</label>";

        var divLittle1 = document.createElement('div');
        divLittle1.classList.add("col-xs-7");
        divLittle1.appendChild(new_input);

        var divLittle2 = document.createElement('div');
        divLittle2.classList.add("col-xs-2");
        divLittle2.appendChild(new_select_type);

        var divLittle3 = document.createElement('div');
        divLittle3.classList.add("col-xs-1");
        divLittle3.appendChild(new_input1);

        var divLittle4 = document.createElement('div');
        divLittle4.classList.add("col-xs-2");
        divLittle4.appendChild(new_input1);
        divLittle4.innerHTML = '<input style="margin-bottom: 15px" type="button" class="btn btn-danger" value="Видалити" onclick="deleteBlock(' + length + ')">';

        var new_input2 = document.createElement("input");
        new_input2.classList.add("form-control");
        new_input2.style.marginBottom = "10px";
        new_input2.name = "components_name["+length+"]";
        new_input2.placeholder = "Назва інгредієнта";

        var divRow = document.createElement('div');
        divRow.classList.add("row");


        divRow.appendChild(divLittle1);
        divRow.appendChild(divLittle2);
        divRow.appendChild(divLittle3);
        divRow.appendChild(divLittle4);

        div.appendChild(new_input2);
        div.appendChild(divRow);

        components.appendChild(div);
        length++;
    } ;
</script>

<div class="form-group {{ $errors->has('complexity') ? 'has-error' : '' }}">

  <label for="complexity" class="control-label">
    Складність рецепту
  </label>

  <select name="complexity" class="form-control" value="{{ old('complexity', @$resipes->complexity) }}">
    @foreach($resipes->complexityTypes as $type)
      <option {{ ($resipes->complexity == $type) ? 'selected' : '' }} value="{{$type}}">{{$type}}</option>
    @endforeach
  </select>
</div>

<div class="form-group {{ $errors->has('cooking_method') ? 'has-error' : '' }}">

  <label for="cooking_method" class="control-label">
    Спосіб приготування
  </label>

  <select name="cooking_method" class="form-control" value="{{ old('cooking_method', @$resipes->cooking_method) }}">
    @foreach($resipes->cookingMethodTypes as $type)
      <option {{ ($resipes->cooking_method == $type) ? 'selected' : '' }} value="{{$type}}">{{$type}}</option>
    @endforeach
  </select>
</div>

<div class="form-group {{ $errors->has('recipes') ? 'has-error' : '' }}">

  <label for="recipes" class="control-label">
    Опис рецепту
  </label>

  <textarea
          name="recipes"
          id="recipes"
          placeholder="recipes"
          class="form-control">{{ old('recipes', @$resipes->recipes) }}</textarea>

  @if ($errors->has('recipes'))
    <div class="help-block">
      {{ $errors->first('recipes') }}
    </div>
  @endif
</div>




<div class="form-group">
  <button type="submit" class="btn btn-success">Зберегти</button>
  <a href="/recipes" class="btn btn-default">До списку</a>
</div>

resources/views/resipes/index.blade.php
@extends('layouts.app')

@section('content')
  <style>
    .alert-danger {
      background-color: #f2dede !important;
    }
    .alert-success {
      background-color: #dff0d8 !important;
    }
  </style>

  <div class="container">

    <div class="clearfix">
      <div class="pull-left">
        <div class="lead">Рецепти</div>
      </div>
      <div class="pull-right">
        <a href="/recipes/add" class="btn btn-success">Додати</a>
      </div>
    </div>

    <hr>

    <div class="col-xs-12" style="overflow-x: auto">
    <table class="table table-bordered table-hover table-striped">
      <thead>
      <tr>
        <th class="col-xs-3">
          Назва рецепту
          <div class="pull-right">
            <a href="?sortby=title&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('name', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=title&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('name', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-3">
          Складність приготування
          <div class="pull-right">
            <a href="?sortby=complexity&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('created_at', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=complexity&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('created_at', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-2">
          Спосіб приготування
          <div class="pull-right">
            <a href="?sortby=cooking_method&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('created_at', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=cooking_method&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('created_at', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>
        </th>
        <th class="col-xs-2">
          Можливість приготування
          {{--<div class="pull-right">
            <a href="?sortby=finish_prod&sortdir=ASC"
               class="btn btn-xs {{ is_active_sorter('finish_prod', 'ASC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-up"></i>
            </a>
            <a href="?sortby=finish_prod&sortdir=DESC"
               class="btn btn-xs {{ is_active_sorter('finish_prod', 'DESC') ? 'btn-primary' : 'btn-default' }}">
              <i class="fa fa-arrow-down"></i>
            </a>
          </div>--}}
        </th>
        <th class="col-xs-2">

        </th>
      </tr>
      </thead>
      <tbody>
      @foreach($resipes as $res)
          <?php
          if ($components = $res->components) {
              $can = 'can';
              foreach ($components as $component) {
                  $product = $user->productComponent($component['name']);

                  if (isset($product['name'])) {
                      if ($product['count'] * $coef->typeKoef[$product['count_type']] >= $component['count'] * $coef->typeKoef[$component['count_type']]) {
                          continue;
                      }
                  }

                  if ($component['possibility_of_replacement'] == 'on') {
                      continue;
                  }
                  $can = 'cannot';
              }
          }
          ?>
        <tr class="{{($can == 'cannot') ? 'alert-danger' : 'alert-success'}}">
          <td>
            <a href="/recipes/{{ $res->id }}">{{ $res->title }}</a>
          </td>
          <td>
              {{ $res->complexity }}
          </td>
          <td>
              {{ $res->cooking_method }}
          </td>
          <td>


            {{ ($can == 'cannot') ? 'Недостатньо продуктів' : 'Можливо' }}

          </td>
          <td>
            <div class="input-group-btn">
              <a href="{{ route('recipes.edit', $res->id) }}" class="btn btn-primary">Редагувати</a>
              <a href="{{ route('recipes.delete', $res->id) }}" class="btn btn-danger"
                 onclick="return confirm('Впевнені що хочете видалити рецепт?');">
                Видалити
              </a>
            </div>
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>
    </div>

    <div class="text-center">
      {{--{!! $pages->appends(request()->except('page'))->links() !!}--}}
    </div>

  </div>
@endsection

resources/views/resipes/show.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .alert-danger {
            background-color: #f2dede !important;
        }

        .alert-success {
            background-color: #dff0d8 !important;
        }

        .alert-warning {
            background-color: #fcf8e3 !important;
        }
    </style>

    <div class="container">

        <h2>{{ $resipes->title }}


            <div class="pull-right">
                <a href="/recipes" class="btn btn-default">До списку</a>
            </div>
        </h2>

        <hr>

        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>Інгредієнт</th>
                <th>Кількість</th>
                <th>Можливість змінення</th>
            </tr>
            @if($components = $resipes->components)
                @foreach($components as $component)
                    <?php
                    $can = 'cannot';

                    $product = $user->productComponent($component['name']);

                    if ($component['possibility_of_replacement'] == 'on') {
                        $can = 'maybe';
                    }

                    if (isset($product['name'])) {
                        if ($product['count'] * $coef->typeKoef[$product['count_type']] >= $component['count'] * $coef->typeKoef[$component['count_type']]) {
                            $can = 'can';
                        }
                    }

                    ?>
                    <tr class="{{($can == 'can') ? 'alert-success' : (($can == 'maybe') ? 'alert-warning' : 'alert-danger')}}">
                        <td>{{$component->name}}</td>
                        <td>{{$component->count}} {{$component->count_type}}</td>
                        <td>{{($component->possibility_of_replacement == 'on') ? 'Можливе замінення' : 'Ні'}}</td>
                    </tr>
                @endforeach
            @endif
        </table>

        <hr>

        <div>
            {!! $resipes->recipes !!}
        </div>

    </div>

@endsection